/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { ConsoleLogger } from "./console-logger.js";
import { mountNpmDocs } from "./utils/npm.js";
import { mountGoDocs } from "./utils/gomodule.js";

export async function createMCPServer(deps: {
  package: string;
  registry: string;
  logger: ConsoleLogger;
  subDir?: string | undefined;
  mcpPrimitive: "tool" | "resource";
}) {
  const server = new McpServer({
    name: "Supporting Markdown Docs",
    version: "0.0.1",
  });

  switch (deps.registry) {
    case "npm":
      await mountNpmDocs(server, deps.package, deps.logger, deps.mcpPrimitive, deps.subDir);
      break;
    case "gomodules":
      await mountGoDocs(server, deps.package, deps.logger, deps.mcpPrimitive, deps.subDir);
      break;
    default:
      throw new Error(`Unsupported registry: ${deps.registry}`);
  }

  return server;
}
